import Link from "next/link";
import { ArrowRight, ArrowUpRight, GitBranch, Landmark, Scale, Waves } from "lucide-react";

export const metadata = { title: "Parampara — JalSaarthi X" };

export default function ParamparaPage() {
  return <main className="editorial-page">
    <div className="editorial-kicker"><span className="eyebrow-dot" /> INDIAN WATER KNOWLEDGE / 01</div>
    <div className="editorial-hero"><div><h1>Old systems.<br /><em>New questions.</em></h1><p>The Eri tradition points to a powerful idea: storage, channels, and communities work as a connected whole. JalSaarthi X turns that idea into an inspectable demonstration.</p><Link href="/" className="button-primary editorial-cta">Explore the model <ArrowRight size={17} /></Link></div><div className="editorial-aside"><span>01 — 04</span><div className="water-line-art"><Waves size={112} strokeWidth={0.65} /></div><p>One network. Four tanks.<br />Multiple downstream effects.</p></div></div>
    <section className="editorial-section"><div className="section-heading"><span>01 / TRADITION</span><h2>The Eri cascade</h2></div><div className="editorial-copy"><p>An <em>Eri</em> is a Tamil irrigation tank. In a cascade, connected tanks can collect runoff, store water, serve nearby land, and pass surplus downstream through channels and weirs. Maintenance of those links matters to tail-end users.</p><p>This is the concept we model. The four-tank network in the workspace is invented for teaching; it does not trace an actual village or claim one universal Eri operating rule.</p></div></section>
    <section className="principle-grid" aria-label="Principles translated into software"><div><span className="principle-icon"><GitBranch size={22} /></span><small>01 / CONNECTION</small><h3>Water moves through links.</h3><p>Tanks and channels form a directed graph. A blocked link changes what downstream tanks can receive.</p></div><div><span className="principle-icon"><Waves size={22} /></span><small>02 / SURPLUS</small><h3>Storage before overflow.</h3><p>After local demand, each tank retains water up to capacity. Remaining water moves onward or exits the modeled network.</p></div><div><span className="principle-icon"><Scale size={22} /></span><small>03 / SHARING</small><h3>Rules shape outcomes.</h3><p>Compare a simplified household-first allocation with proportional allocation. This is a configurable model rule, not a historical universal.</p></div></section>
    <section className="editorial-section sources-section"><div className="section-heading"><span>02 / EVIDENCE</span><h2>Grounded context.<br /><em>Explicit assumptions.</em></h2></div><div className="editorial-copy"><p>These sources support the historical and infrastructure context. They do <strong>not</strong> validate the demo rainfall, repair costs, efficiencies, or predicted field impact.</p><a href="https://www.frontiersin.org/journals/water/articles/10.3389/frwa.2025.1597293/full" target="_blank" rel="noreferrer">Mailam tank-cascade study, Frontiers in Water <ArrowUpRight size={17} /></a><a href="https://www.tnagrisnet.tn.gov.in/fcms/documents/go/agri_e_ms_87_ae2_2023.pdf" target="_blank" rel="noreferrer">Tamil Nadu order on tail-end irrigation and channel maintenance <ArrowUpRight size={17} /></a><a href="https://icid-ciid.org/award/his_details/154" target="_blank" rel="noreferrer">ICID description of Veeranam Tank <ArrowUpRight size={17} /></a></div></section>
    <div className="editorial-end"><Landmark size={19} /><span>Traditional knowledge is the starting point. Measured, locally agreed inputs are required for real decisions.</span></div>
  </main>;
}
