import Link from "next/link";
import { ArrowRight, ArrowUpRight, CircleCheck, CircleDashed, Database, Gauge, ShieldCheck } from "lucide-react";

export const metadata = { title: "About — JalSaarthi X" };

export default function AboutPage() {
  return <main className="editorial-page about-page">
    <div className="editorial-kicker"><span className="eyebrow-dot" /> PROJECT METHODOLOGY / 02</div>
    <div className="editorial-hero"><div><h1>A clear model.<br /><em>Honest limits.</em></h1><p>JalSaarthi X is a software-only engineering demonstration for exploring how a damaged channel changes delivery across an Eri-inspired tank network.</p><Link href="/" className="button-primary editorial-cta">Open the workspace <ArrowRight size={17} /></Link></div><div className="editorial-aside"><span>METHOD / 01</span><div className="water-line-art"><Gauge size={108} strokeWidth={0.65} /></div><p>Every displayed water quantity comes from the deterministic simulation.</p></div></div>
    <section className="editorial-section"><div className="section-heading"><span>01 / HOW IT WORKS</span><h2>Traceable by design.</h2></div><div className="editorial-copy"><p>The browser loads one typed, illustrative fixture. Rainfall becomes runoff in litres. Tanks serve demand, retain water within capacity, then send surplus through directed channels. Broken connections transfer nothing. Every litre is delivered, stored, lost in-channel, or counted as external spill.</p><p>The repair optimizer tests every affordable combination of up to eight eligible actions against the same inputs. It minimizes unmet demand, then cost, action count, and repair ID. Groq can optionally parse a written defect into an editable proposal; it never generates hydrological numbers.</p></div></section>
    <section className="method-list"><div><span className="method-icon"><Database size={20} /></span><div><h3>Illustrative inputs</h3><p>Four tanks, three channels, three villages, and a single rainfall event. All numeric values and repair prices are invented for reproducible demonstration.</p></div><span>01</span></div><div><span className="method-icon"><CircleCheck size={20} /></span><div><h3>Conserved water balance</h3><p>Initial storage + runoff = delivery + final storage + channel loss + external spill. The engine rejects a non-zero residual.</p></div><span>02</span></div><div><span className="method-icon"><ShieldCheck size={20} /></span><div><h3>Bounded repair search</h3><p>Deterministic exhaustive search compares feasible repairs under the entered budget. The user applies any recommendation explicitly.</p></div><span>03</span></div></section>
    <section className="editorial-section limitations-section"><div className="section-heading"><span>02 / LIMITATIONS</span><h2>What this model<br /><em>does not claim.</em></h2></div><div className="editorial-copy"><ul><li>No surveyed village topology or measured repair cost.</li><li>No infiltration, evaporation, groundwater, travel time, hydraulic head, or sediment model.</li><li>No rainfall forecast, sensor feed, or field-validated water-saving prediction.</li><li>No engineering certification or replacement for community consultation.</li></ul><p>Real planning requires calibrated data, site inspection, hydraulic review, and locally agreed allocation rules. The present model is a transparent way to ask better questions.</p></div></section>
    <div className="editorial-end"><CircleDashed size={19} /><span>Read the full specification in the <a href="https://github.com/piyushaggarwal1322009-bit/JAL-DHARA/tree/main/documentation" target="_blank" rel="noreferrer">project documentation <ArrowUpRight size={15} /></a>.</span></div>
  </main>;
}
